-- Émergence (horloges de progression « Blades in the Dark ») : compteurs par Partie.
-- État dynamique de jeu, rattaché au Playthrough (comme sessions / quest_progression).
-- Compatible Postgres et H2 (MODE=PostgreSQL).
create table clocks (
    id bigint generated by default as identity,
    playthrough_id bigint not null,
    name varchar(255) not null,
    description text,
    segments integer not null,
    filled integer not null,
    "order" integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);
create index ix_clock_playthrough on clocks (playthrough_id);
