-- Fronts (menaces regroupant des horloges) par Partie + rattachement optionnel des horloges.
-- État de jeu, comme les horloges. Compatible Postgres et H2 (MODE=PostgreSQL).
create table fronts (
    id bigint generated by default as identity,
    playthrough_id bigint not null,
    name varchar(255) not null,
    description text,
    "order" integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);
create index ix_front_playthrough on fronts (playthrough_id);

-- Une horloge peut appartenir à un Front (null = horloge libre).
alter table clocks add column front_id bigint;
