
    create table quests (
        "order" integer not null,
        campaign_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        description TEXT,
        gm_notes TEXT,
        icon varchar(255),
        illustration_image_ids TEXT,
        name varchar(255) not null,
        narrative_stakes TEXT,
        nodes TEXT,
        player_objectives TEXT,
        prerequisites TEXT,
        related_page_ids TEXT,
        primary key (id)
    );

    create index ix_quests_campaign
       on quests (campaign_id);
