package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 * Niveau 1 — Backfill des Quests depuis les chapitres existants (migration ADDITIVE).
 *
 * <p>Chaque chapitre qui jouait le rôle de quête devient une {@code Quest} avec le
 * MÊME id (continuité d'id, décision D4 en migration in‑place). Critère aligné sur
 * la règle runtime réelle ({@code SessionStructuralContextBuilder} : une quête =
 * {@code arc HUB} OU {@code chapitre porteur de prérequis}), + filet « tout chapitre
 * déjà référencé par une progression » pour ne perdre aucun état.</p>
 *
 * <p>Comme l'id est partagé, les {@code Prerequisite.QuestCompleted.questId} (qui
 * valaient un chapterId) restent valides verbatim, et la bascule ultérieure de
 * {@code quest_progression.chapter_id → quest_id} sera une simple copie. Migration
 * en Java (et non SQL) pour le seul point non portable : le reset de la séquence
 * d'identité côté Postgres après insertion d'ids explicites.</p>
 */
public class V10__Backfill_quests_from_chapters extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection conn = context.getConnection();
        try (Statement st = conn.createStatement()) {

            // 1) Backfill : on réutilise l'id du chapitre comme id de quête.
            //    Le nœud d'origine (le chapitre) est ajouté comme premier QuestNodeRef.
            st.executeUpdate(
                "INSERT INTO quests (id, campaign_id, \"order\", name, description, icon, " +
                "prerequisites, nodes, gm_notes, player_objectives, narrative_stakes, " +
                "related_page_ids, illustration_image_ids, created_at, updated_at) " +
                "SELECT c.id, a.campaign_id, c.\"order\", c.name, c.description, c.icon, " +
                "c.prerequisites, " +
                "'[{\"nodeType\":\"CHAPTER\",\"nodeId\":\"' || CAST(c.id AS VARCHAR) || '\",\"order\":0}]', " +
                "c.gm_notes, c.player_objectives, c.narrative_stakes, " +
                "c.related_page_ids, c.illustration_image_ids, c.created_at, c.updated_at " +
                "FROM chapters c JOIN arcs a ON c.arc_id = a.id " +
                "WHERE a.type = 'HUB' " +
                "   OR (c.prerequisites IS NOT NULL AND c.prerequisites <> '' AND c.prerequisites <> '[]') " +
                "   OR c.id IN (SELECT chapter_id FROM quest_progression)"
            );

            // 2) Reset de la séquence d'identité de `quests`.
            //    Les ids ont été insérés EXPLICITEMENT (continuité avec les chapitres).
            //    Ni Postgres ni H2 (MODE=PostgreSQL) n'ajustent la séquence d'un
            //    GENERATED BY DEFAULT AS IDENTITY sur insertion explicite → sans reset,
            //    une Quest créée ensuite par l'appli réutiliserait un id déjà pris.
            long nextId;
            try (ResultSet rs = st.executeQuery("SELECT COALESCE(MAX(id), 0) FROM quests")) {
                rs.next();
                nextId = rs.getLong(1) + 1;
            }
            String product = conn.getMetaData().getDatabaseProductName();
            boolean isPostgres = product != null && product.toLowerCase().contains("postgresql");
            if (isPostgres) {
                st.execute("SELECT setval(pg_get_serial_sequence('quests', 'id'), " + nextId + ", false)");
            } else {
                // H2 (MODE=PostgreSQL) : RESTART WITH repositionne la séquence d'identité.
                st.execute("ALTER TABLE quests ALTER COLUMN id RESTART WITH " + nextId);
            }
        }
    }
}
