package com.loremind.infrastructure.persistence.migration;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Régression (Niveau 1) : le runner legacy {@code PlaythroughMigrationRunner.migrateProgressions}
 * insérait dans {@code quest_progression.chapter_id}, colonne renommée en {@code quest_id} par V11.
 * Les tests create-drop ne couvraient pas ce chemin (la colonne legacy
 * {@code chapters.progression_status} n'existe pas dans le schéma Hibernate), d'où un crash au
 * démarrage sur une BDD Postgres existante. Ce test rejoue le runner sur un schéma H2
 * {@code MODE=PostgreSQL} contenant la colonne legacy + un {@code quest_progression} post-V11.
 */
class PlaythroughMigrationRunnerProgressionTest {

    private String url;
    private Connection keepAlive;
    private JdbcTemplate jdbc;

    @BeforeEach
    void setUp() throws Exception {
        // DATABASE_TO_LOWER=TRUE : H2 plie les identifiants non quotés en minuscules comme Postgres,
        // pour que les sondes information_schema (table_name/column_name en minuscules) du runner matchent.
        url = "jdbc:h2:mem:pmr_" + UUID.randomUUID().toString().replace("-", "")
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";
        keepAlive = DriverManager.getConnection(url, "sa", "");
        jdbc = new JdbcTemplate(new DriverManagerDataSource(url, "sa", ""));

        // chapters porte la colonne LEGACY progression_status ; quest_progression est en schéma post-V11.
        jdbc.execute("create table campaigns (id bigint primary key)");
        jdbc.execute("create table arcs (id bigint primary key, campaign_id bigint not null)");
        jdbc.execute("create table chapters (id bigint primary key, arc_id bigint not null, progression_status varchar(16))");
        jdbc.execute("create table playthroughs (id bigint primary key, campaign_id bigint not null)");
        jdbc.execute("create table quest_progression ("
                + "id bigint generated by default as identity primary key, "
                + "playthrough_id bigint not null, quest_id bigint not null, status varchar(16) not null)");
    }

    @AfterEach
    void tearDown() throws Exception {
        if (keepAlive != null) keepAlive.close();
    }

    @Test
    void migrateProgressions_usesQuestIdColumn_andIsIdempotent() {
        jdbc.update("insert into campaigns (id) values (1)");
        jdbc.update("insert into arcs (id, campaign_id) values (10, 1)");
        jdbc.update("insert into chapters (id, arc_id, progression_status) values (100, 10, 'IN_PROGRESS')");
        jdbc.update("insert into chapters (id, arc_id, progression_status) values (101, 10, 'NOT_STARTED')"); // ignoré
        jdbc.update("insert into playthroughs (id, campaign_id) values (50, 1)");

        PlaythroughMigrationRunner runner = new PlaythroughMigrationRunner();

        int migrated = runner.migrateProgressions(jdbc);
        assertEquals(1, migrated, "Seul le chapitre 100 (IN_PROGRESS) doit migrer.");

        List<Map<String, Object>> rows = jdbc.queryForList(
                "select playthrough_id, quest_id, status from quest_progression");
        assertEquals(1, rows.size());
        assertEquals(50L, ((Number) rows.get(0).get("playthrough_id")).longValue());
        assertEquals(100L, ((Number) rows.get(0).get("quest_id")).longValue(),
                "quest_id == id du chapitre (continuité d'id).");
        assertEquals("IN_PROGRESS", rows.get(0).get("status"));

        // Idempotence : 2e passage n'insère rien (NOT EXISTS sur quest_id).
        assertEquals(0, runner.migrateProgressions(jdbc));
    }
}
